apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - image: 59678892/udagram-api-feed:v1
        name: udagram-api-feed 
        imagePullPolicy: Always  
        env:
        - name: URL
          value: http://localhost:8080
        - name: JWT_SECRET
          value: hello
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_HOST
          value: mydbpro3.c1ql7fgcgter.us-east-1.rds.amazonaws.com
        - name: POSTGRES_PASSWORD
          value: luutheduy
        - name: POSTGRES_USERNAME
          value: postgres
        - name: AWS_BUCKET
          value: project3-196005-dev
      restartPolicy: Always
